[workspace]
members = [
    "crates/bevy-city",
    "crates/renderware-format",
    "crates/renderware-format-converter",
    "crates/renderware-format-dumper",
    "crates/bevy_renderware",
]
resolver = "2"