[package]
name = "renderware-format-dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
renderware-format = { path = "../../crates/renderware-format" }
